### ISSUE TITLE
RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

### ISSUE THREAD

**Issue by agnieszkajust** [google-research/vision_transformer#40]
I use this command: 
python3 -m vit_jax.train --name ViT-B_16-my_dataset_`date +%F_%H%M%S` --model ViT-B_16 --logdir /tmp/vit_logs --dataset my_dataset --batch 8 --batch_eval 8 
and gets in the console:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/vit_jax/train.py", line 229, in <module>
    main(parser.parse_args())
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/vit_jax/train.py", line 165, in main
    opt_repl, loss_repl, update_rngs = update_fn_repl(
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 133, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/api.py", line 1481, in f_pmapped
    out = pxla.xla_pmap(
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/core.py", line 1216, in bind
    return call_bind(self, fun, *args, **params)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/core.py", line 1180, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/core.py", line 1219, in process
    return trace.process_map(self, fun, tracers, params)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/core.py", line 583, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 512, in xla_pmap_impl
    return compiled_fun(*args)
  File "/home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/env/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 954, in execute_replicated
    out_bufs = compiled.execute_on_local_devices(list(input_bufs))
RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

CUDA Version: 11.0 
python 3.8
tensorflow               2.3.1
jax                      0.2.6
jaxlib                   0.1.57+cuda110
joblib                   0.17.0

**Comment by andsteing** [comment]
What `DATASET_PRESETS` are you using for `my_dataset` ?

**Comment by agnieszkajust** [comment]
It's my own dataset, created with this tutorial: https://www.tensorflow.org/datasets/add_dataset

**Comment by andsteing** [comment]
So what values did you add to `DATASET_PRESETS` ?

https://github.com/google-research/vision_transformer/blob/ba9a85bdc430daf4da7b9da67b486a4e0f5bb278/vit_jax/input_pipeline.py#L32-L54

**Comment by agnieszkajust** [comment]
DATASET_PRESETS = {
    'cifar10': {
        'train': 'train[:98%]',
        'test': 'test',
        'resize': 384,
        'crop': 384,
        'total_steps': 10_000,
    },
    'cifar100': {
        'train': 'train[:98%]',
        'test': 'test',
        'resize': 384,
        'crop': 384,
        'total_steps': 10_000,
    },
    'imagenet2012': {
        'train': 'train[:99%]',
        'test': 'validation',
        'resize': 384,
        'crop': 384,
        'total_steps': 20_000,
    },
    'my_dataset': {
            'train': 'train',
            'test': 'test',
            'resize': 128,
            'crop': 128,
            'total_steps': 20_000,
        },
}

**Comment by andsteing** [comment]
Did you manage to run the models with the default datasets (e.g. `cifar10`) ?

What GPU are you running on? The default flags `--batch=512 --accum-steps=16` were tested on a 8x V100 GPU machine. You should thus be able to run `--batch_size=64` on a single V100 with 16G memory. It looks like you might have a bit less memory pressure since your input images are smaller.

**Comment by agnieszkajust** [comment]
When i try to run on dataset cifar10, I get the same result: RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well). 
I have RTX 2060.

**Comment by agnieszkajust** [comment]
I solved it but now after training I get an error related to saving the model to the indicated folder:
File "/home/vision_transformer/env/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 545, in rename_v2
    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/agnieszka/Documents/sieci_kategoryzacyjne/vision_transformer/output/-TEMPORARY; Directory not empty

Why?

**Comment by czh4** [comment]
@agnieszkajust How did you solve the runtime error?
